version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file: docker/dev.env

  web:
    command: /home/wait-for-it.sh db:5432 -- ./docker/start.sh
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: docker/dev.env
    volumes:
      - .:/code
    depends_on:
      - db

  nginx:
    image: nginx
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - .:/src
      - ./docker/nginx:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web
